### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"husddseo@hd1usse.chxdl",
    "password":"1235",
    "test":"test"
}

### Get the currently user signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST  http://localhost:3000/auth/signout

### Signin for a user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"husddseo@hd1usse.chxdl",
    "password":"1o235",
    "test":"test"
}

### Find a prticular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=husse@husse.cc

### Delete user with a given ID
DELETE http://localhost:3000/auth/9

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    # "email":"husse@husse1211.cc"
    "password":"12999"
}

### Set a color
GET http://localhost:3000/auth/colors/red

### Get the colors
GET http://localhost:3000/auth/colors